use_frameworks!

platform :ios, '10.0'

target 'XKSquarifiedMap_Example' do
  pod 'XKSquarifiedMap', :path => '../'
  
  pod 'SnapKit'
  pod 'SwifterSwift'

  target 'XKSquarifiedMap_Tests' do
    inherit! :search_paths

    
  end
end
